# This creates a list of file locations for tweets

name: TweetListUpdater

# Controls when the workflow will run
on:
  # Triggers the workflow on push requests to the main branch only if there is a change to the schema or example in tweets directory
  push:
    branches: [ main ]
    paths: 
      - 'tweets/**/*.json'

  workflow_dispatch:

jobs:

  update:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Updates list of example filepaths
      - name: Writes new list of files
        run: find "$TWEET_DIRECTORY" -type f -name '*.json' | sed "s#$TWEET_DIRECTORY##" > $FILENAME
        env:
          TWEET_DIRECTORY: 'tweets/'
          FILENAME: 'exampleFilepaths.txt'
      
      - name: Commits new file
        uses: test-room-7/action-update-file@v1
        with:
            file-path: exampleFilepaths.txt
            commit-msg: Update list of tweet filepaths in repo
            github-token: ${{ secrets.GITHUB_TOKEN }}
          
