# This is a basic workflow to help you get started with Actions

name: FileListUpdater

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
      - 'tweets/**/*.json'
      - 'schema.json'
  pull_request:
    branches: [ main ]
    paths: 
      - 'tweets/**/*.json'
      - 'schema.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  update:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Updates list of example filepaths
      - name: Writes new list of files
        run: find "$TWEET_DIRECTORY" -type f -name '*.json' | sed "s#$TWEET_DIRECTORY##" > $FILENAME
        env:
          TWEET_DIRECTORY: 'tweets/'
          FILENAME: 'exampleFilepaths.txt'
      
      - name: Commits new file
        uses: test-room-7/action-update-file@v1
        with:
            file-path: exampleFilepaths.txt
            commit-msg: Update list of tweet filepaths in repo
            github-token: ${{ secrets.GITHUB_TOKEN }}

  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run validation
      run: python "$VALIDATION_SCRIPT" "$SCHEMA_FILE" "$EXAMPLES_DIR"
      env:
        VALIDATION_SCRIPT: "scripts/exampleValidation.py"
        SCHEMA_FILE: "schema.json"
        EXAMPLES_DIR: "tweets/"
          
